data = [
    {'name': 'Instagram', 'follower_count': 674, 'description': 'Social media platform', 'country': 'USA'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 652, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 504, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 420, 'description': 'Singer & Actress', 'country': 'USA'},
    {'name': 'Dwayne “The Rock” Johnson', 'follower_count': 394, 'description': 'Actor & Producer', 'country': 'USA'},
    {'name': 'Kylie Jenner', 'follower_count': 393, 'description': 'Media Personality & Entrepreneur', 'country': 'USA'},
    {'name': 'Ariana Grande', 'follower_count': 375, 'description': 'Singer & Actress', 'country': 'USA'},
    {'name': 'Kim Kardashian', 'follower_count': 356, 'description': 'Media Personality', 'country': 'USA'},
    {'name': 'Beyoncé', 'follower_count': 311, 'description': 'Singer & Actress', 'country': 'USA'},
    {'name': 'Khloé Kardashian', 'follower_count': 303, 'description': 'Media Personality', 'country': 'USA'},
    {'name': 'Justin Bieber', 'follower_count': 294, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Taylor Swift', 'follower_count': 280, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Kendall Jenner', 'follower_count': 286, 'description': 'Media Personality', 'country': 'USA'},
    {'name': 'National Geographic', 'follower_count': 277, 'description': 'Magazine brand', 'country': 'USA'},
    {'name': 'Neymar', 'follower_count': 231, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Nicki Minaj', 'follower_count': 224, 'description': 'Musician', 'country': 'USA'},
    {'name': 'Miley Cyrus', 'follower_count': 212, 'description': 'Singer & Actress', 'country': 'USA'},
    {'name': 'Katy Perry', 'follower_count': 203, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Zendaya', 'follower_count': 178, 'description': 'Actress & Singer', 'country': 'USA'},
    {'name': 'Kylian Mbappé', 'follower_count': 125, 'description': 'Footballer', 'country': 'France'},
    {'name': 'Gal Gadot', 'follower_count': 107, 'description': 'Actress', 'country': 'Israel'},
    {'name': 'Vin Diesel', 'follower_count': 103, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Lisa (BLACKPINK)', 'follower_count': 106, 'description': 'Musician', 'country': 'Thailand'},
    {'name': 'Kim Taehyung (V)', 'follower_count': 68, 'description': 'Musician (BTS member)', 'country': 'South Korea'},
    {'name': 'BTS (official)', 'follower_count': 77, 'description': 'Music group', 'country': 'South Korea'},
    {'name': 'Virat Kohli', 'follower_count': 270, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Shraddha Kapoor', 'follower_count': 94, 'description': 'Actress', 'country': 'India'},
    {'name': 'Priyanka Chopra', 'follower_count': 92.5, 'description': 'Actress & Producer', 'country': 'India'},
    {'name': 'Narendra Modi', 'follower_count': 92.4, 'description': 'Prime Minister', 'country': 'India'},
    {'name': 'Alia Bhatt', 'follower_count': 86.2, 'description': 'Actress & Producer', 'country': 'India'},
    {'name': 'Katrina Kaif', 'follower_count': 80.4, 'description': 'Actress', 'country': 'India'},
    {'name': 'Deepika Padukone', 'follower_count': 80.4, 'description': 'Actress & Producer', 'country': 'India'},
    {'name': 'Neha Kakkar', 'follower_count': 78.4, 'description': 'Playback Singer', 'country': 'India'},
    {'name': 'Urvashi Rautela', 'follower_count': 72.5, 'description': 'Actress & Model', 'country': 'India'},
    {'name': 'Jacqueline Fernandez', 'follower_count': 71.1, 'description': 'Actress', 'country': 'India'},
    {'name': 'Sachin Tendulkar', 'follower_count': 50.3, 'description': 'Former Cricketer', 'country': 'India'},
    {'name': 'MS Dhoni', 'follower_count': 49.2, 'description': 'Former Cricketer', 'country': 'India'},
    {'name': 'Rohit Sharma', 'follower_count': 42.8, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Hardik Pandya', 'follower_count': 39.2, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Team India', 'follower_count': 37.6, 'description': 'Cricket team account', 'country': 'India'},
    {'name': 'National Geographic', 'follower_count': 277, 'description': 'Magazine / Media Brand', 'country': 'USA'},
    {'name': 'Nike', 'follower_count': 300, 'description': 'Sportswear Brand', 'country': 'USA'},
    {'name': 'Real Madrid', 'follower_count': 177, 'description': 'Football Club', 'country': 'Spain'},
    {'name': 'FC Barcelona', 'follower_count': 142, 'description': 'Football Club', 'country': 'Spain'},
    {'name': 'NASA', 'follower_count': 96, 'description': 'Space Agency', 'country': 'USA'},
    {'name': 'Victoria’s Secret', 'follower_count': 72, 'description': 'Lingerie / Retail Brand', 'country': 'USA'},
    {'name': 'Huda Beauty', 'follower_count': 50, 'description': 'Makeup Brand', 'country': 'UAE'},
    {'name': 'Chanel', 'follower_count': 50, 'description': 'Fashion House', 'country': 'France'},
    {'name': 'Zara', 'follower_count': 50, 'description': 'Fashion Retail Brand', 'country': 'Spain'},
    {'name': 'Gucci', 'follower_count': 48, 'description': 'Fashion House', 'country': 'Italy'},
    {'name': 'Marvel', 'follower_count': 68, 'description': 'Entertainment Brand', 'country': 'USA'},
    {'name': 'Bugatti', 'follower_count': 21.6, 'description': 'Luxury Auto Brand', 'country': 'France'},
    {'name': 'Apple', 'follower_count': 31.9, 'description': 'Technology Brand', 'country': 'USA'},
    {'name': 'Porsche', 'follower_count': 28.9, 'description': 'Automotive Brand', 'country': 'Germany'},
    {'name': 'Ferrari', 'follower_count': 27.8, 'description': 'Automotive Brand', 'country': 'Italy'},
    {'name': 'PlayStation', 'follower_count': 30.8, 'description': 'Gaming Brand', 'country': 'USA'},
    {'name': 'GoPro', 'follower_count': 20.7, 'description': 'Imaging & Adventure Brand', 'country': 'USA'},
    {'name': '9GAG', 'follower_count': 50, 'description': 'Entertainment / Meme Media', 'country': 'Global'},
    {'name': 'Pubity (Meme publisher)', 'follower_count': 40, 'description': 'Gen‑Z social content', 'country': 'UK'},
    {'name': 'The Dogist', 'follower_count': 7.3, 'description': 'Pet photography media', 'country': 'USA'},
]

